; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Wed Jun 09 2021 21:02:13 GMT+0200 (Mitteleuropäische Sommerzeit)

