; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Wed Jun 09 2021 21:02:13 GMT+0200 (Mitteleuropäische Sommerzeit)
G1 H1 X160 Y130 F3600
M558 F1000 A1
G30
M558 F1000 A10
G30

; Uncomment the following lines to lift Z after probing
G91              ; relative positioning
G1 Z5 F100       ; lift Z relative to current position
G90              ; absolute positioning

